// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug() {
  return window['go']['main']['WailsBinds']['Debug']();
}

export function GetContent(arg1) {
  return window['go']['main']['WailsBinds']['GetContent'](arg1);
}

export function GetLatestId() {
  return window['go']['main']['WailsBinds']['GetLatestId']();
}

export function GetTitle(arg1) {
  return window['go']['main']['WailsBinds']['GetTitle'](arg1);
}

export function IsRunningGopherTunnel() {
  return window['go']['main']['WailsBinds']['IsRunningGopherTunnel']();
}

export function KillGopherTunnel() {
  return window['go']['main']['WailsBinds']['KillGopherTunnel']();
}

export function Logging(arg1) {
  return window['go']['main']['WailsBinds']['Logging'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['main']['WailsBinds']['NeedsUpdate'](arg1);
}

export function RunGopherTunnel(arg1, arg2) {
  return window['go']['main']['WailsBinds']['RunGopherTunnel'](arg1, arg2);
}
