// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog():Promise<void>;

export function Debug():Promise<void>;

export function GetContent(arg1:number):Promise<string>;

export function GetLatestId():Promise<number>;

export function GetTitle(arg1:number):Promise<string>;

export function IsRunningGopherTunnel():Promise<boolean>;

export function KillGopherTunnel():Promise<void>;

export function Logging(arg1:string):Promise<void>;

export function NeedsUpdate(arg1:number):Promise<boolean>;

export function RunGopherTunnel(arg1:string,arg2:string):Promise<void>;
